services:
  app:
    # Use platform linux/amd64 to match Cloud Run environment exactly
    platform: linux/amd64
    image: ghcr.io/tung68nt/tulie_crm:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
